export enum ActionTypes {
    ADD_INGRIDIENTS,
    REMOVE_INGRIDIENTS,
    SET_INGRIDIENTS,
    FETCH_INGRIDIENTS_FAILED,
    PURCHASE_BURGER_SUCCESS,
    PURCHASE_BURGER_FAIL,
    PURCHASE_BURGER_LOADING,
    PURCHASE_INIT,
    FETCH_ORDERS_LOADING,
    FETCH_ORDERS_SUCCESS,
    FETCH_ORDERS_FAILL,
    AUTH_LOADING,
    AUTH_SUCCESS,
    AUTH_FAIL,
    AUTH_LOGOUT,
    SET_AUTH_REDIRECT_PATH

}
